### PR TITLE
Fix 4:4:4 intra prediction 

### LINKED ISSUE #86: 4:4:4 inter- failure
Conformance tests utilising 4:4:4 colour and inter-prediction are currently failing.

### PR DESCRIPTION
**Pull request by frankplow**
It seems as though the `V_DIAG` mode should not be used when using Direct Mode MIP. To be honest, I don't see how this is implemented in the specification, so there's probably a better way to implement this. The only relevant clause I see in the specification is:
>If treeType is equal to SINGLE_TREE, sps_chroma_format_idc is equal to 3, intra_chroma_pred_mode is equal to 4, and IntraMipFlag[ xCb ][ yCb ] is equal to 1, the following applies:
>– The MIP chroma direct mode flag MipChromaDirectFlag[ xCb ][ yCb ] is set equal to 1.
>– The chroma intra prediction mode IntraPredModeC[ xCb ][ yCb ] is set equal to IntraPredModeY[ xCb ][ yCb ].

however this is already implemented and has the additional condition `intra_chroma_pred_mode == 4`.

As is, this fix appears to work however. I will make a PR in [ffvvc/tests](https://github.com/ffvvc/tests) to reflect the tests which now pass later.

This PR will fix #86.

### CODE REVIEW

**Comment by nuomi2021** [comment]
@frankplow , thank you, I will check it next week.

File: libavcodec/vvc/vvc_ctu.c [hunk 1]
```diff
@@ -892,10 +892,15 @@ static void derive_chroma_intra_pred_mode(VVCLocalContext *lc,
         const int modes[4] = {INTRA_PLANAR, INTRA_VERT, INTRA_HORZ, INTRA_DC};
         int idx;
 
-        for (idx = 0; idx < FF_ARRAY_ELEMS(modes); idx++) {
-            if (modes[idx] == luma_intra_pred_mode)
-                break;
+        if (cu->tree_type == SINGLE_TREE && sps->chroma_format_idc == CHROMA_FORMAT_444 && intra_mip_flag) {
```
Comment (nuomi2021) [inline libavcodec/vvc/vvc_ctu.c:895]: please give some comments on why we need this workaround and attach the spec issue link https://jvet.hhi.fraunhofer.de/trac/vvc/ticket/1602
thank you

**Comment by frankplow** [comment]
The spec issue has been resolved (https://jvet.hhi.fraunhofer.de/trac/vvc/ticket/1602). This PR now implements the fix in the manner dictated by the standard.

File: libavcodec/vvc/vvc_ctu.c [hunk 2]
```diff
@@ -865,8 +865,12 @@ static enum IntraPredMode derive_center_luma_intra_pred_mode(const VVCFrameConte
     const int cu_pred_mode        = SAMPLE_CTB(fc->tab.cpm[0], x_center, y_center);
     const int intra_pred_mode_y   = SAMPLE_CTB(fc->tab.ipm, x_center, y_center);
 
-    if (intra_mip_flag)
-        return INTRA_PLANAR;
+    if (intra_mip_flag) {
+        if (cu->tree_type == SINGLE_TREE && sps->chroma_format_idc == CHROMA_FORMAT_444)
+            return -1;
```
Comment (nuomi2021) [inline libavcodec/vvc/vvc_ctu.c:870]: how about define INTRA_INVALID

Comment (frankplow) [reply libavcodec/vvc/vvc_ctu.c]: Done in 71c1841716c4b7c8778f54a6b9080856577cbac4.

I think `INTRA_DEFAULT` is a little more fitting as `-1` is now valid - see change to table 20 in spec fix.

File: libavcodec/vvc/vvc_ctu.h [hunk 3]
```diff
@@ -162,6 +162,7 @@ typedef enum PredFlag {
 } PredFlag;
 
 typedef enum IntraPredMode {
+    INTRA_DEFAULT   = -1,
```
Comment (nuomi2021) [inline libavcodec/vvc/vvc_ctu.h:165]: invalid is a better name. Because we have no such Intra predict model. 
since it invalid, we fallback to default

File: libavcodec/vvc/vvc_ctu.c [hunk 4]
```diff
@@ -865,8 +865,12 @@ static enum IntraPredMode derive_center_luma_intra_pred_mode(const VVCFrameConte
     const int cu_pred_mode        = SAMPLE_CTB(fc->tab.cpm[0], x_center, y_center);
     const int intra_pred_mode_y   = SAMPLE_CTB(fc->tab.ipm, x_center, y_center);
 
-    if (intra_mip_flag)
-        return INTRA_PLANAR;
+    if (intra_mip_flag) {
+        if (cu->tree_type == SINGLE_TREE && sps->chroma_format_idc == CHROMA_FORMAT_444)
+            return INTRA_DEFAULT;
+        else
```
Comment (nuomi2021) [inline libavcodec/vvc/vvc_ctu.c:871]: else is not needed, you can return INTRA_PLANAR directly. 
thank you

Comment (frankplow) [reply libavcodec/vvc/vvc_ctu.c]: Done in 6e7b9747700a06ba1427f74aa0050ec70e243338

File: libavcodec/vvc/vvc_ctu.h (hunk 3 above)
Comment (frankplow) [reply libavcodec/vvc/vvc_ctu.h]: Done in 6e7b9747700a06ba1427f74aa0050ec70e243338

**Comment by nuomi2021** [comment]
thank you. @frankplow
